casestudy/urls.py
from django.conf.urls import url

from .views import IndexView, DetailView

urlpatterns = [
	url(r'^$', IndexView.as_view(), name="index"),
	url(r'^(?P<pk>[0-9]+)/$', DetailView.as_view(), name="detail"),
]

portfolio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^', include('casestudy.urls', namespace='casestudy')),
    url(r'^admin/', include(admin.site.urls)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

casestudy/models.py
from django.db import models

# Create your models here.
class CaseStudy(models.Model):
	name = models.CharField(max_length="200")
	description = models.TextField()

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'case studies'

class Item(models.Model):
	casestudy = models.ForeignKey(CaseStudy)
	title = models.CharField(max_length="200")
	photo = models.ImageField(upload_to="items/%Y/%m/%d")
	description = models.TextField()

	def __unicode__(self):
		return self.title

casestudy/views.py
from django.shortcuts import render
from django.views import generic

from .models import CaseStudy, Item

# Create your views here.
class IndexView(generic.ListView):
	template_name = 'casestudy/index.html'
	model = CaseStudy

class DetailView(generic.DetailView):
	model = CaseStudy
	template_name = 'casestudy/detail.html'

casestudy/templates/casestudy/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block 'content' %}
<h1>{{ casestudy.name }}</h1>

{% if casestudy.item_set %}
<table>

{% for item in casestudy.item_set.all %}

<tr>
	<td colspan='2'>{{ item.title }}</td>
</tr>

<tr>
	{% thumbnail item.photo "300x300" crop="center" as im %}
	<td><img src="{{ im.url }}"></td>
	{% endthumbnail %}
	<td>{{ item.description }}</td>
</tr>


{% endfor %}

</table>



{% endif %}

{% endblock %}

casestudy/templates/casestudy/index.html
{% extends 'base.html' %}
{% block 'title' %}List of Case studies{% endblock %}

{% block 'content' %}
{% if casestudy_list %}
	<h1>Here are my case studies</h1>
	<ul>
	{% for study in casestudy_list %}

	<li><a href="{% url 'casestudy:detail' study.id %}">{{study.name}}</a> - {{study.description}}</li>

	{% endfor %}
	</ul>

{% else %}

	<p>No case studies to show.</p>

{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block 'title' %}Welcome to my site{% endblock %}</title>

    <!-- Bootstrap core CSS -->
<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Django</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="Admin">Admin</a></li>
            <li><a href="mailto:d00241719@dmail.dixie.edu">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" style="margin-top: 50px;">
{% block 'content' %}
      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
{% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>